### ISSUE TITLE
你好，请问lobe-chat的OPENAI_PROXY_URL填写方法

### ISSUE THREAD

**Issue by alexallen1** [aurora-develop/aurora#185]
我在docker compose启动ChatGPT-Next-Web
填入下面是能用的
 BASE_URL=http://myvps:8080

但在lobe-chat照搬好像不行，使用的范例

```
version: '3.8'
 
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    environment:
      OPENAI_API_KEY: sk-xxxx
      OPENAI_PROXY_URL: http://myvps:8080
```

这样填入,
OPENAI_PROXY_URL: http://myvps:8080
提示
```
{
  "error": {
    "cause": {
      "errno": -111,
      "code": "ECONNREFUSED",
      "syscall": "connect",

    }
  },
  "endpoint": "http://myvps:8080",
  "provider": "openai"
}
```
请教解决方法~
